// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMnoHDGfrXB5_Fj-tTSLxlkKLKfY7jjo',
    appId: '1:333242787419:web:421efb29ac7cb959b2817e',
    messagingSenderId: '333242787419',
    projectId: 'cybershield-160de',
    authDomain: 'cybershield-160de.firebaseapp.com',
    storageBucket: 'cybershield-160de.firebasestorage.app',
    measurementId: 'G-2JDJW1MDSV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFWnl0poRPpL8kircoNOT-Jx-HMGzcxBM',
    appId: '1:333242787419:android:93ae4e93ad21cfb0b2817e',
    messagingSenderId: '333242787419',
    projectId: 'cybershield-160de',
    storageBucket: 'cybershield-160de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZj2aaPp7PuV3nWFH6miY_LY63s11B5tw',
    appId: '1:333242787419:ios:71b3ebe098631f7bb2817e',
    messagingSenderId: '333242787419',
    projectId: 'cybershield-160de',
    storageBucket: 'cybershield-160de.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZj2aaPp7PuV3nWFH6miY_LY63s11B5tw',
    appId: '1:333242787419:ios:71b3ebe098631f7bb2817e',
    messagingSenderId: '333242787419',
    projectId: 'cybershield-160de',
    storageBucket: 'cybershield-160de.firebasestorage.app',
    iosBundleId: 'com.example.finalYearProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwMnoHDGfrXB5_Fj-tTSLxlkKLKfY7jjo',
    appId: '1:333242787419:web:51d123c27bdcc44cb2817e',
    messagingSenderId: '333242787419',
    projectId: 'cybershield-160de',
    authDomain: 'cybershield-160de.firebaseapp.com',
    storageBucket: 'cybershield-160de.firebasestorage.app',
    measurementId: 'G-31Y2YL0DTV',
  );
}
